
all : array-1d array-2d call-external-function call-function coercao do-while for funcao hello if-1 if-2 instrucoes-logicas-aritmeticas leia-escreva modulo phi repeat-until scanf sum vars while

	make -C ./array-1d/C/
	make -C array-2d/C/
	make -C call-external-function/C/
	make -C call-function/C/
	make -C coercao/C/ 
	make -C do-while/C/
	make -C for/C/ 
	make -C funcao/C/ 
	make -C hello/C/
	make -C if-1/C/
	make -C if-2/C/
	make -C instrucoes-logicas-aritmeticas/C/
	make -C leia-escreva/C/
	make -C modulo/C/
	make -C phi/C/
	make -C repeat-until/C/
	make -C scanf/C/
	make -C sum/C/
	make -C vars/C/
	make -C while/C/



clean : array-1d array-2d call-external-function call-function coercao do-while for funcao hello if-1 if-2 instrucoes-logicas-aritmeticas leia-escreva modulo phi repeat-until scanf sum vars while

	make -C ./array-1d/C/ clean
	make -C array-2d/C/ clean
	make -C call-external-function/C/ clean
	make -C call-function/C/ clean
	make -C coercao/C/ clean 
	make -C do-while/C/ clean
	make -C for/C/ clean 
	make -C funcao/C/ clean 
	make -C hello/C/ clean
	make -C if-1/C/ clean
	make -C if-2/C/ clean
	make -C instrucoes-logicas-aritmeticas/C/ clean
	make -C leia-escreva/C/ clean
	make -C modulo/C/ clean
	make -C phi/C/ clean
	make -C repeat-until/C/ clean
	make -C scanf/C/ clean
	make -C sum/C/ clean
	make -C vars/C/ clean
	make -C while/C/ clean
